apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: cafe-canary.example.com
    http:
      paths:
      - path: /coffee
        backend:
          serviceName: canary-demo
          servicePort: 80
