apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout-cafe.yaml
- analysis-success-rate.yaml
- cafe-canary-demo-service.yaml
- cafe-canary-demo-ingress.yaml
- cafe-canary-demo-preview-service.yaml
- cafe-canary-demo-preview-ingress.yaml
- hpa.yaml
